source 'http://rubygems.org'

# main
gem 'rails', '3.0.9'
gem 'rake'
gem 'rack' #, '1.2.3'
# gem 'rails', :git => 'git://github.com/rails/rails.git'

# DBs
# gem 'sqlite3'
gem 'mysql2'
gem 'mysql'
gem 'pg'

# models addons
gem 'foreigner'
gem 'composite_primary_keys' #, '=3.1.0'
gem 'default_value_for'
gem 'will_paginate', " >= 3.0.pre4" #, " >= 3.0.pre2"
gem 'acts_as_commentable'

# auth
# https://github.com/binarylogic/authlogic/blob/master/README.rdoc
gem 'authlogic'

# rights managament
# https://github.com/ryanb/cancan/blob/master/README.rdoc
gem 'cancan'

# web sockets
gem 'em-websocket'

# rails addons
# https://github.com/andi/simple-navigation/wiki/Dynamic-Navigation-Items
gem 'simple-navigation'
gem 'formtastic'
gem 'haml'
gem 'sass'

# JS
gem 'jquery-rails'

# coffee
gem 'json'
gem 'coffee-script', '~> 2.1.1'
gem 'coffee-haml-filter'
gem 'rack-coffee'
#gem 'bistro_car'
gem 'barista'

# backend addons
gem 'geokit'
gem 'json'
gem 'robustthread'

# probably not used anywhere
gem 'hpricot'

# web servers
# gem 'unicorn'
# gem 'thin'

# probably not used
# gem 'mini_magick'





# Deploy with Capistrano
#gem 'capistrano'
#require "bundler/capistrano"

# debug
# gem 'ruby-debug'
# gem 'ruby-debug19'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

#gem 'jrails'
#gem "backbone-rails", "~> 0.3.3.1"
#gem 'backbone_rails'

# https://github.com/probablycorey/mini_magick/blob/master/README.rdoc
# http://pullmonkey.com/projects/open_flash_chart/view_source_code/y_right
#gem 'open_flash_chart'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
