source 'http://rubygems.org'

gem 'rails', '3.0.3'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2'

# Use unicorn as the web server
# gem 'unicorn'

# faster, but probably not best for development
# http://code.macournoyer.com/thin/
gem 'thin'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
gem 'ruby-debug'
# gem 'ruby-debug19'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

gem 'haml'
gem 'default_value_for'

# has error 'can't convert nil into Array'
gem 'will_paginate', " >= 3.0.pre2"

# https://github.com/andi/simple-navigation/wiki/Dynamic-Navigation-Items
gem 'simple-navigation'

gem 'formtastic'

# https://github.com/ryanb/cancan/blob/master/README.rdoc
gem 'cancan'

# https://github.com/binarylogic/authlogic/blob/master/README.rdoc
gem 'authlogic', :git => 'git://github.com/odorcicd/authlogic.git', :branch => 'rails3'

gem 'jrails'

# https://github.com/probablycorey/mini_magick/blob/master/README.rdoc
gem 'mini_magick'

# http://pullmonkey.com/projects/open_flash_chart/view_source_code/y_right
#gem 'open_flash_chart'

gem 'geokit'

# ...
# http://ruby-toolbox.com/

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
