# Definitions of measurements
---
# In normal situation all measurements has it's own thread and fetch measurements every
# some interval. Using 'one thread' all measurements are fetched in one thread.
:one_thread: false
# Interval per type are ignored, there is only one for all measurements
:one_thread_interval: 0.4
# Save all measurements from special pool every this number of seconds
:measurement_pool_flush_interval: 10

:array:
  # codename of measurement
  - :name: batt_u
    :locale:
      :en: "Batteries voltage"
      :pl: "Napięcie na akumulatorach"
    # store_to_buffer in memory X last measurements
    :cache: 100
    :unit: V
    :log_conditions:
      # log no frequent than every X seconds
      :min: 0.2
      # log at least every X seconds
      :max: 300
      # significant change of value which enforce logging
      #:sig_change: 2
      :sig_change: 1
      # if offline is true measurements are added to pool and stored every (5-20) seconds
      # this parameters is set in :measurement_pool_flush_interval
      :offline: true
      #:offline: false
    # parameters used only for simulator
    :simulator:
      :default_value: 48.0
  # command sent to uC
    :command:
      # interval how often fetch from uC
      # 1 is about 100ms
      # 50 is about 5s
      :frequency: 1
      # command array, array of String chars or Fixnum bytes
      :array:
        - '0'
      #  - 48
      # number of bytes of response
      :response_size: 2
      # coefficients for processing from raw to real
      :coefficient_linear: 0.0777126099706744868
      :coefficient_offset: 0