#!/usr/bin/ruby
#encoding: utf-8

# This file is part of HomeIO.
#
#    HomeIO is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    HomeIO is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
 

require 'rubygems'
require 'rake'
require 'rake/clean'
require 'rake/gempackagetask'
require 'rake/rdoctask'
require 'rake/testtask'

spec = Gem::Specification.new do |s|
  s.name = 'WindServer_SVN'
  s.version = '0.0.1'
  s.has_rdoc = true
  s.extra_rdoc_files = ['README', 'LICENSE']
  s.summary = 'Your summary here'
  s.description = s.summary
  s.author = ''
  s.email = ''
  # s.executables = ['your_executable_here']
  s.files = %w(LICENSE README Rakefile) + Dir.glob("{bin,lib,spec}/**/*")
  s.require_path = "lib"
  s.bindir = "bin"
end

Rake::GemPackageTask.new(spec) do |p|
  p.gem_spec = spec
  p.need_tar = true
  p.need_zip = true
end

Rake::RDocTask.new do |rdoc|
  files =['README', 'LICENSE', 'lib/**/*.rb']
  rdoc.rdoc_files.add(files)
  rdoc.main = "README" # page to start on
  rdoc.title = "WindServer_SVN Docs"
  rdoc.rdoc_dir = 'doc/rdoc' # rdoc output folder
  rdoc.options << '--line-numbers'
end

Rake::TestTask.new do |t|
  t.test_files = FileList['test/**/*.rb']
end

# addition taks
namespace :db do

  desc 'Initialize DBs'
  task :init do
    require './lib/storage/storage.rb'
    Storage.instance.init
  end

  desc 'Initialize DBs (some dev fixes)'
  task :init_tmp do
    require './lib/storage/storage.rb'
    StorageActiveRecord.instance
    ActiveRecordInitMigration2.up
  end

  desc 'Clean DBs'
  task :deinit do
    require './lib/storage/storage.rb'
    Storage.instance.deinit
  end

  desc 'Populate cities'
  task :pop_cities do
    require './lib/storage/storage.rb'
    StorageActiveRecord.instance
    City.create_from_config
  end

end

namespace :metar do

  # file name for setting which cities process
  DEFINED_CITIES_TO_PROCESS_FILE = 'RakeCitiesToProcess.yml'
  # when true defined cities are processed in reverse order
  REVERSE_CITIES = true

  namespace :process do

    desc 'Process all metars logged in raw format'
    task :all do
      #require './lib/metar_logger.rb'
      #MetarLogger.instance.processor.process_all
      require './lib/metar/metar_mass_processor.rb'
      MetarMassProcessor.instance.process_all
    end

    desc 'Process all CITY metars logged in raw format'
    task :city do
      require './lib/metar_logger.rb'
      puts MetarLogger.instance.get_logged_cities.collect{|c| "#{c[:code]} - #{c[:name]} (#{c[:country]})"}.join("\n")

      puts "Choose city:"
      city = STDIN.gets.strip

      if metar_cities.select{|c| c[:code] == city}.size == 1
        puts "Processing #{city}"
        MetarMassProcessor.instance.process_all_for_city( city )
      end
    end

    desc "Create list of all logged cities in '#{DEFINED_CITIES_TO_PROCESS_FILE}'"
    task :redefine do
      require './lib/metar_logger.rb'
      cities =  MetarLogger.instance.get_logged_cities.collect{|c| c[:code]}
      File.open( DEFINED_CITIES_TO_PROCESS_FILE, 'w' ) do |out|
        YAML.dump( cities, out )
      end
    end

    desc "Process all cities from '#{DEFINED_CITIES_TO_PROCESS_FILE}'"
    task :predefined do
      require './lib/metar/metar_mass_processor.rb'
      cities = YAML::load_file( DEFINED_CITIES_TO_PROCESS_FILE )
      cities = cities.reverse if REVERSE_CITIES == true
      cities.each do |c|
        MetarMassProcessor.instance.process_all_for_city( c )
      end
    end
  end
end

# stars server
namespace :supervisor do

  desc 'Start supervisor server without IM'
  task :start_no_im do
    require './lib/supervisor/supervisor.rb'
    s = Supervisor.instance
    s.start
  end

  desc 'Start supervisor server without IM'
  task :start do
    require './lib/supervisor/supervisor.rb'
    s = Supervisor.instance
    s.start
  end


  desc 'Start supervisor server with IM'
  task :start_with_im do
    require './lib/plugins/im/im_bots.rb'
    im = ImBots.instance
    im.start

    # TODO crashing, why?
    sleep(1)

    require './lib/supervisor/supervisor.rb'
    s = Supervisor.instance
    s.start
  end

  desc 'Start IM bots'
  task :im do
    require './lib/plugins/im/im_bots.rb'
    im = ImBots.instance
    im.start

    puts "IM bots started at #{Time.now}"
    loop do
      sleep 10
    end
  end

end

# tcp commands

namespace :client do

  desc 'Ping server'
  task :ping do
    require './lib/supervisor/supervisor_client.rb'
    command = {:command => :ping, :now => true}
    response = SupervisorClient.send_to_server_non_wait( command )
    puts response.inspect
  end

  desc 'Test command processor'
  task :test do
    require './lib/supervisor/supervisor_client.rb'
    command = {:command => :test}
    response = SupervisorClient.send_to_server_non_wait( command )
    puts response.inspect
  end

  desc 'Test command processor (wait)'
  task :test_wait do
    require './lib/supervisor/supervisor_client.rb'
    command = {:command => :test_wait}
    response = SupervisorClient.send_to_server_and_wait( command )
    puts response.inspect
  end

  desc 'Fetch queue'
  task :queue do
    require 'yaml'
    require './lib/supervisor/supervisor_client.rb'
    puts SupervisorClient.get_queue.to_yaml
  end

  #  # TODO write interface, need priorities and threads
  #  desc 'Process METAR for city'
  #  task :process_metar_city do
  #    require './lib/supervisor/supervisor_client.rb'
  #    #command = {:command => :process_metar_city, :city => 'EPPO', :now => true}
  #    command = {:command => :process_metar_city, :city => 'EPPO'}
  #    response = SupervisorClient.new.send_to_server( command )
  #    puts response.inspect
  #  end

  # Send task to queue
  desc 'Fetch weather (non wait)'
  task :fetch_weather do
    require './lib/supervisor/supervisor_client.rb'
    command = {:command => :fetch_weather}
    response = SupervisorClient.send_to_server( command )
    puts response.inspect
  end

  # Send task and wait for answer
  desc 'Fetch weather (wait for end)'
  task :fetch_weather_wait do
    require './lib/supervisor/supervisor_client.rb'
    command = {:command => :fetch_weather}
    response = SupervisorClient.send_to_server_and_wait( command )
    puts response.inspect
  end

  # Send task and do it now
  desc 'Fetch weather (now!)'
  task :fetch_weather_now do
    require './lib/supervisor/supervisor_client.rb'
    command = {:command => :fetch_weather}
    response = SupervisorClient.send_to_server_non_wait( command )
    puts response.inspect
  end


  # Send task to queue
  desc 'Fetch METAR (non wait)'
  task :fetch_metar do
    require './lib/supervisor/supervisor_client.rb'
    command = {:command => :fetch_metar}
    response = SupervisorClient.send_to_server( command )
    puts response.inspect
  end

  # Send task and wait for answer
  desc 'Fetch METAR (wait)'
  task :fetch_metar_wait do
    require './lib/supervisor/supervisor_client.rb'
    command = {:command => :fetch_metar}
    response = SupervisorClient.send_to_server_and_wait( command )
    puts response.inspect
  end

  # Send task and do it now
  desc 'Fetch METAR (now!)'
  task :fetch_metar_now do
    require './lib/supervisor/supervisor_client.rb'
    command = {:command => :fetch_metar}
    response = SupervisorClient.send_to_server_non_wait( command )
    puts response.inspect
  end


end

namespace :action do

  desc 'Fetch weather (supervisor not needed)'
  task :fetch_weather do
    t = Time.now
    require './lib/weather_ripper.rb'
    w = WeatherRipper.instance
    w.fetch
    puts "Time: #{Time.now.to_f - t.to_f}"
  end

  desc 'Fetch weather and then metar (supervisor not needed)'
  task :fetch_weather_metar do
    t = Time.now
    require './lib/weather_ripper.rb'
    w = WeatherRipper.instance
    w.fetch

    require './lib/metar_logger.rb'
    Thread.abort_on_exception = true
    m = MetarLogger.instance
    output = m.fetch_and_store
    puts "Time: #{Time.now.to_f - t.to_f}"
  end

  desc 'Fetch METAR (supervisor not needed)'
  task :fetch_metar do
    t = Time.now
    require './lib/metar_logger.rb'
    Thread.abort_on_exception = true
    m = MetarLogger.instance
    output = m.fetch_and_store
    puts "Time: #{Time.now.to_f - t.to_f}"
  end

end



namespace :gems do

  desc 'Install required gems'
  task :install do
    `gem install geokit`
    `gem install mysql`
    `gem install serialport`
    `gem install hpricot`
    `gem install rmagick`
  end

end

