source 'http://rubygems.org'

# redis with pure C driver
gem "hiredis"
gem 'redis', :require => ["redis/connection/hiredis", "redis"]

# https://github.com/brianmario/yajl-ruby
gem 'yajl-ruby'

group :development do
  gem 'pry'

  gem "rdoc"
  gem "rspec"
  gem "bundler"
  gem "jeweler"
  gem "simplecov"
end