source 'http://rubygems.org'

gem 'redis'
# https://github.com/brianmario/yajl-ruby
gem 'yajl'

group :development do
  gem 'pry'

  gem "rdoc"
  gem "rspec"
  gem "bundler"
  gem "jeweler"
  gem "simplecov"
end