source 'http://rubygems.org'

# redis with pure C driver
gem "hiredis"
gem 'redis', :require => ["redis/connection/hiredis", "redis"]

# cron-like stuff
gem "rufus-scheduler"

# https://github.com/brianmario/yajl-ruby
gem 'yajl-ruby'

# weather service
gem 'weather_fetcher' #, :git => 'git://github.com/akwiatkowski/weather_fetcher.git'

group :development do
  gem 'pry'

  gem "rdoc"
  gem "rspec"
  gem "bundler"
  gem "jeweler"
  gem "simplecov"
end