# Definitions of measurements

:array:
  - :name: batt_u
    :unit: V
    :storage:
      min_time_interval: 0.5
      max_time_interval: 3600

      avg_side_count: 10 # X before, this, and X after
      value_deviation: 1.0

      store_interval: 600

    :command:
      - '3'
    :response_size: 2
    :coefficients:
      :linear: 0.0777126099706744868
      :offset: 0

  - :name: i_gen_batt
    :unit: A
    :storage:
      min_time_interval: 0.5
      max_time_interval: 3600

      avg_side_count: 20 # X before, this, and X after
      value_deviation: 1.0

      store_interval: 600

    :command:
      - '4'
    :response_size: 2
    :coefficients:
      :linear: 0.191
      :offset: -512

  - :name: i_gen_resist
    :unit: A
    :storage:
      min_time_interval: 1.0
      max_time_interval: 7200

      avg_side_count: 10
      value_deviation: 2.5

      store_interval: 1200

    :command:
      - '5'
    :response_size: 2
    :coefficients:
      :linear: 0.191
      :offset: -512

  - :name: i_inverters
    :unit: A
    :storage:
      min_time_interval: 1.0
      max_time_interval: 7200

      avg_side_count: 10
      value_deviation: 2.5

      store_interval: 1800

    :command:
      - '6'
    :response_size: 2
    :coefficients:
      :linear: 0.191
      :offset: -512


  - :name: imp_per_min
    :unit: "ipm/min"
    :storage:
      min_time_interval: 1.0
      max_time_interval: 7200

      avg_side_count: 20
      value_deviation: 250

      store_interval: 600

    :command:
      - 'l'
    :response_size: 2
    :coefficients:
      :linear: 60.0
      :offset: 0



  - :name: coil_1_u
    :unit: V
    :storage:
      min_time_interval: 0.5
      max_time_interval: 3600

      avg_side_count: 30 # X before, this, and X after
      value_deviation: 3.0

      store_interval: 600

    :command:
      - '0'
    :response_size: 2
    :coefficients:
      :linear: 0.0777126099706744868
      :offset: 0


  - :name: coil_2_u
    :unit: V
    :storage:
      min_time_interval: 0.5
      max_time_interval: 3600

      avg_side_count: 30 # X before, this, and X after
      value_deviation: 3.0

      store_interval: 600

    :command:
      - '1'
    :response_size: 2
    :coefficients:
      :linear: 0.0777126099706744868
      :offset: 0

  - :name: coil_3_u
    :unit: V
    :storage:
      min_time_interval: 0.5
      max_time_interval: 3600

      avg_side_count: 30 # X before, this, and X after
      value_deviation: 3.0

      store_interval: 600

    :command:
      - '2'
    :response_size: 2
    :coefficients:
      :linear: 0.0777126099706744868
      :offset: 0

#

  - :name: res_pwm
    :unit: lvl
    :storage:
      min_time_interval: 1.0
      max_time_interval: 7200

      avg_side_count: 0 # X before, this, and X after
      value_deviation: 5.0

      store_interval: 1200

    :command:
      - 'p'
    :response_size: 2
    :coefficients:
      :linear: 1.0
      :offset: 0

  - :name: res_pwm_avg
    :unit: lvl
    :storage:
      min_time_interval: 1.0
      max_time_interval: 7200

      avg_side_count: 0 # X before, this, and X after
      value_deviation: 4.0

      store_interval: 1200

    :command:
      - 'q'
    :response_size: 2
    :coefficients:
      :linear: 1.0
      :offset: 0


  - :name: big_inv_status
    :unit: lvl
    :storage:
      min_time_interval: 1.0
      max_time_interval: 7200

      avg_side_count: 0 # X before, this, and X after
      value_deviation: 1.0

      store_interval: 3600

    :command:
      - 'u'
    :response_size: 2
    :coefficients:
      :linear: 1.0
      :offset: 0


  - :name: outputs
    :unit: bit vector
    :storage:
      min_time_interval: 1.0
      max_time_interval: 7200

      avg_side_count: 0 # X before, this, and X after
      value_deviation: 1.0

      store_interval: 3600

    :command:
      - 'o'
    :response_size: 1
    :coefficients:
      :linear: 1.0
      :offset: 0
