# Storing into Sqlite DB
#
# Sqlite is optional engine used only for storing
---
:enabled: false
# filename of various dbs
:db_file_meas: 'meas'
:db_file_weather: 'weather'
:db_file_metar_weather: 'metar'
#  definitions, tables, ...
:classes:
  # class name
  :MetarCode:
    # how many object should be stored one time
    #:pool_size: 100
    :pool_size: 500
    # table name
    :table_name: 'metar_weather_archives'
  # weather
  :Weather:
    :pool_size: 100
    :table_name: 'weather_archives'
