---
:db_host: localhost
:db_base_online: wiatrak2
:db_base_offline: wiatrak2_test
# used for all independent for online communication
:db_base: wiatrak2

:db_table_meas: meas_archives
:db_table_weather: weather_archives
:db_table_weather_metar: weather_metar_archives

:db_login: wiatrak
:db_password: antek
# when something goes wrong
:query_file: "data/queries_archive.sql"
# where store logs
:logger_path: "data/DbStore.log"

:sq_lite_file_meas: "data/DBmeas.sqlite3"
:sq_lite_file_weather: "data/DBweather.sqlite3"
:sq_lite_file_metar_weather: "data/DBmetar_weather.sqlite3"