--- 
- !ruby/object:HomeIoMeasElement 
  code: u_aku
  desc: napiecie akumulatorow
  desc_u: "Napięcie akumulatorów"
  log_value:
  log_time:
  log_min_interval: 1.0
  log_max_interval: 300.0
  offline_max_value: 63.0
  offline_min_value: 40.0
  offline_sig_change: 10.0
  sig_change: 0.8
  time: 2000-01-01 00:00:00 +01:00
  unit: V
  type: :float
  unit_scaler: 0.0777126099706744868 
  unit_offset: 0
  command: 51
  bytes: 2
  value:
  refresh_interval: 1.0
- !ruby/object:HomeIoMeasElement 
  code: i_gen_aku
  desc: prad lad. akumulatorow
  desc_u: "Prąd ładowania akumulatorów"
  log_value:
  log_time:   
  log_min_interval: 1.0
  log_max_interval: 300.0
  offline_max_value: 20.0
  offline_min_value: 0.0
  offline_sig_change: 8.0
  sig_change: 0.8
  time: 2000-01-01 00:00:00 +01:00
  unit: A
  type: :float
  unit_scaler: 0.191
  unit_offset: -512
  command: 52
  bytes: 2
  value:
  refresh_interval: 0.5

- !ruby/object:HomeIoMeasElement 
  code: i_gen_obciaz
  desc: prad grzalki
  desc_u: "Prąd grzałki"
  log_value:
  log_time: 
  log_min_interval: 1.0
  log_max_interval: 300.0
  offline_max_value: 8.0
  offline_min_value: 0.0
  offline_sig_change: 4.0
  sig_change: 1.4
  time: 2000-01-01 00:00:00 +01:00
  unit: A
  type: :float
  unit_scaler: 0.191
  unit_offset: -512
  command: 53
  bytes: 2
  value:
  refresh_interval: 2.0
- !ruby/object:HomeIoMeasElement 
  code: i_aku_przetw
  desc: prad przetwornicy
  desc_u: "Prąd przetwornicy"
  log_value:
  log_time:
  log_min_interval: 1.0
  log_max_interval: 300.0
  offline_max_value: 15.0
  offline_min_value: 0.0
  offline_sig_change: 7.0
  sig_change: 1.6
  time: 2000-01-01 00:00:00 +01:00
  unit: A
  type: :float
  unit_scaler: 0.191
  unit_offset: -512
  command: 54
  bytes: 2
  value:
  refresh_interval: 5.0
  
- !ruby/object:HomeIoMeasElement 
  code: impulsow_na_min
  desc: impulsy z generatora
  desc_u: "Impulsy z generatora"
  log_value:
  log_time: 
  log_min_interval: 1.0
  log_max_interval: 300.0
  offline_max_value: 5000
  offline_min_value: 0
  offline_sig_change: 2000.0
  sig_change: 250.0
  time: 2000-01-01 00:00:00 +01:00
  unit: imp
  type: :int
  unit_scaler: 60.0
  unit_offset: 0
  command: 108
  bytes: 2
  value:
  refresh_interval: 3.0
  
- !ruby/object:HomeIoMeasElement 
  code: u_cewka_1
  desc: cewka 1
  desc_u: "Napięcie cewki 1"
  log_value:
  log_time: 
  log_min_interval: 1.0
  log_max_interval: 300.0
  offline_max_value: 50.0
  offline_min_value: 0.0
  offline_sig_change: 24.0
  sig_change: 10.0
  time: 2000-01-01 00:00:00 +01:00
  unit: V
  type: :float
  unit_scaler: 0.0777126099706744868 
  unit_offset: 0
  command: 48
  bytes: 2
  value:
  refresh_interval: 2.0
- !ruby/object:HomeIoMeasElement 
  code: u_cewka_2
  desc: cewka 2
  desc_u: "Napięcie cewki 2"
  log_value:
  log_time: 
  log_min_interval: 1.0
  log_max_interval: 300.0
  offline_max_value: 50.0
  offline_min_value: 0.0
  offline_sig_change: 24.0
  sig_change: 10.0
  time: 2000-01-01 00:00:00 +01:00
  unit: V
  type: :float
  unit_scaler: 0.0777126099706744868 
  unit_offset: 0
  command: 49
  bytes: 2
  value:
  refresh_interval: 2.0
- !ruby/object:HomeIoMeasElement 
  code: u_cewka_3
  desc: cewka 3
  desc_u: "Napięcie cewki 3"
  log_value: 
  log_time:
  log_min_interval: 1.0
  log_max_interval: 300.0
  offline_max_value: 50.0
  offline_min_value: 0.0
  offline_sig_change: 24.0
  sig_change: 10.0
  time: 2000-01-01 00:00:00 +01:00
  unit: V
  type: :float
  unit_scaler: 0.0777126099706744868 
  unit_offset: 0
  command: 50
  bytes: 2
  value:
  refresh_interval: 2.0
  
- !ruby/object:HomeIoMeasElement 
  code: pwm_now
  desc: wlaczenie grzalki
  desc_u: "Stopień włączenia grzałki"
  log_value:
  log_time: 
  log_min_interval: 1.0
  log_max_interval: 300.0
  offline_max_value: 255
  offline_min_value: 0
  offline_sig_change: 120
  sig_change: 20
  time: 2000-01-01 00:00:00 +01:00
  unit: pwm
  type: :int
  unit_scaler: 1
  unit_offset: 0
  command: 112
  bytes: 2
  value:
  refresh_interval: 2.0
- !ruby/object:HomeIoMeasElement 
  code: pwm_avg
  desc: srednie wl. grzalki
  desc_u: "Średni stopień włączenia grzałki"
  log_value:
  log_time: 
  log_min_interval: 1.0
  log_max_interval: 300.0
  offline_max_value: 255
  offline_min_value: 0
  offline_sig_change: 120
  sig_change: 10
  time: 2000-01-01 00:00:00 +01:00
  unit: pwm
  type: :int
  unit_scaler: 1
  unit_offset: 0
  command: 113
  bytes: 2
  value:
  refresh_interval: 5.0

- !ruby/object:HomeIoMeasElement 
  code: przetw_wlacz
  desc: wlaczona przetwornica
  desc_u: "Włączona przetwornica"
  log_value:
  log_time: 
  log_min_interval: 1.0
  log_max_interval: 300.0
  offline_max_value: 1
  offline_min_value: 0
  offline_sig_change: 1
  sig_change: 1
  time: 2000-01-01 00:00:00 +01:00
  unit: st.
  type: :bool
  unit_scaler: 1
  unit_offset: 0
  command: 117
  bytes: 2
  value:
  refresh_interval: 5.0
