---
:defs:
  - !ruby/object:HomeIoMeasElement 
    # code used when storing
    code: u_aku
    # description
    desc:
      :pl: napiecie akumulatorow
      :en: batteries voltage
    # description (UTF8)
    desc_u:
      :pl: "Napięcie akumulatorów"
      :en: "Batteries voltage"
    # parameters used when storing value in DB
    dbstore:
      :value:
      :time:
      :value:
      # store not more frequent than this
      :min_interval: 1.0
      # store not less frequent than this
      :max_interval: 300.0
      # change of value forcing store
      :sig_change: 0.8
    # simulation, offline mode
    offline:
      :max_value: 63.0
      :min_value: 40.0
      :sig_change: 10.0
    # array, last measurements
    measurements:
     -
    #  - :time:
    #    :value:
    # unit for value
    unit: V
    # class of value
    type: Float
    # value transformation
    transformation:
      :default_scaler: 0.0777126099706744868 
      :default_offset: 0
    # parameters for fetching value
    comm:
      :command: 51
      :bytes: 2
      #:refresh_interval: 1.0
      :refresh_interval: 0.2
    # value of measurement  
    value:
    