# Storing using ActiveRecord
---
:enabled: true
:pool_size: 100
:connection_sqlite:
  #adapter => "mysql",
  #host => "localhost",
  #database => "appdb",
  #username => "appuser",
  #password => "secret"
  adapter: 'sqlite3'
  database: 'data/sqlite/test.sqlite'
:connection_mysql:
  adapter: "mysql"
  host: "localhost"
  database: "appdb"
  username: "appuser"
  password: "secret"
:connection:
  adapter: "mysql"
  host: "localhost"
  database: "homeio"
  username: "homeio"
  password: "homeio"
