# Storing using ActiveRecord
#
# ActiveRecord is mandatory because all data manipulation (extraction and external processing)
# use this
---
# always enabled
#:enabled: true
#:pool_size: 100
:pool_size: 500
:connection_sqlite:
  #adapter => "mysql",
  #host => "localhost",
  #database => "appdb",
  #username => "appuser",
  #password => "secret"
  adapter: 'sqlite3'
  database: 'data/sqlite/test.sqlite'
:connection_mysql:
  adapter: "mysql"
  host: "localhost"
  database: "appdb"
  username: "appuser"
  password: "secret"
:connection:
  adapter: "mysql"
  host: "localhost"
  database: "homeio"
  username: "homeio"
  password: "homeio"
