---
# 0 - first COM/RS port
:port: 0
# 9600, 38400, ...
:baud: 38400
:bits: 8
:stop_port: 1
# none 0
# even 1
# odd 2
:parity: 1

# path for logger
:logger_path: "data/UsartOnline.log"
:verbose_communication: true

# delay before sending [s]
:usart_sleep_pre_send: 0.0005
# delay post sending [s]
:usart_sleep_post_receive: 0.0005