---
:stop_on_error: true
:defs:
#- :url: 'http://pogoda.wp.pl/miasto,inowroclaw,mid,1201072,mi.html'
#  :city: 'Inowrocław'
#  :coord:
#    :lat: 52.799264
#    :lon: 18.259935
#- :url: 'http://pogoda.wp.pl/miasto,mogilno,mid,1201149,mi.html'
#  :city: 'Mogilno'
#  :coord:
#    :lat: 52.658612
#    :lon: 17.955923
- :url: 'http://pogoda.wp.pl/miasto,bydgoszcz,mid,1201023,mi.html'
  :city: 'Bydgoszcz'
  :coord:
    :lat: 53.128893
    :lon: 18.006363
- :url: 'http://pogoda.wp.pl/miasto,torun,mid,1201279,mi.html'
  :city: 'Toruń'
  :coord:
    :lat: 53.019038
    :lon: 18.599052

- :url: 'http://pogoda.wp.pl/miasto,poznan,mid,1201201,mi.html'
  :city: 'Poznań'
  :coord:
    :lat: 52.411048
    :lon: 16.928329
- :url: 'http://pogoda.wp.pl/miasto,warszawa,mid,1201290,mi.html'
  :city: 'Warszawa'
  :coord:
    :lat: 52.237304
    :lon: 21.016617
- :url: 'http://pogoda.wp.pl/miasto,lodz,mid,1201127,mi.html'
  :city: 'Łódź'
  :coord:
    :lat: 51.760743
    :lon: 19.455986
- :url: 'http://pogoda.wp.pl/miasto,kielce,mid,1201091,mi.html'
  :city: 'Kielce'
  :coord:
    :lat: 50.868941
    :lon: 20.629463
- :url: 'http://pogoda.wp.pl/miasto,lublin,mid,1201135,mi.html'
  :city: 'Lublin'
  :coord:
    :lat: 51.248292
    :lon: 22.569237
- :url: 'http://pogoda.wp.pl/miasto,rzeszow,mid,1201227,mi.html'
  :city: 'Rzeszów'
  :coord:
    :lat: 50.044926
    :lon: 22.000694
- :url: 'http://pogoda.wp.pl/miasto,krakow,mid,1201105,mi.html'
  :city: 'Kraków'
  :coord:
    :lat: 50.071508
    :lon: 19.944077

- :url: 'http://pogoda.wp.pl/miasto,katowice,mid,1201086,mi.html'
  :city: 'Katowice'
  :coord:
    :lat: 50.267531
    :lon: 19.023399
#- :url: 'http://pogoda.wp.pl/miasto,jaworzno,mid,1201079,mi.html'
#  :city: 'Jaworzno'
#  :coord:
#    :lat: 50.203847
#    :lon: 19.274712

- :url: 'http://pogoda.wp.pl/miasto,wroclaw,mid,1201305,mi.html'
  :city: 'Wrocław'
  :coord:
    :lat: 51.113265
    :lon: 17.036819
- :url: 'http://pogoda.wp.pl/miasto,zielona-gora,mid,1201320,mi.html'
  :city: 'Zielona Góra'
  :coord:
    :lat: 51.938042
    :lon: 15.506401
- :url: 'http://pogoda.wp.pl/miasto,szczecin,mid,1201268,mi.html'
  :city: 'Szczecin'
  :coord:
    :lat: 53.435147
    :lon: 14.558029
- :url: 'http://pogoda.wp.pl/miasto,koszalin,mid,1201103,mi.html'
  :city: 'Koszalin'
  :coord:
    :lat: 54.195507
    :lon: 16.171074
- :url: 'http://pogoda.wp.pl/miasto,gdansk,mid,1201047,mi.html'
  :city: 'Gdańsk'
  :coord:
    :lat: 54.361598
    :lon: 18.646317
- :url: 'http://pogoda.wp.pl/miasto,olsztyn,mid,1201173,mi.html'
  :city: 'Olsztyn'
  :coord:
    :lat: 53.781708
    :lon: 20.479088
- :url: 'http://pogoda.wp.pl/miasto,suwalki,mid,1201261,mi.html'
  :city: 'Suwałki'
  :coord:
    :lat: 54.114284
    :lon: 22.928352
- :url: 'http://pogoda.wp.pl/miasto,bialystok,mid,1201009,mi.html'
  :city: 'Białystok'
  :coord:
    :lat: 53.137009
    :lon: 23.168678

#- :url: 'http://pogoda.wp.pl/miasto,nowy-targ,mid,1201165,mi.html'
#  :city: 'Nowy Targ'
#  :coord:
#    :lat: 49.478453
#    :lon: 20.031109
#- :url: 'http://pogoda.wp.pl/miasto,zakopane,mid,1201312,mi.html'
#  :city: 'Zakopane'
#  :coord:
#    :lat: 49.301531
#    :lon: 19.949684

